application: prestans-demo
version: 1
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:

- url: /.*
  script: entry.app

